### ISSUE TITLE
Unable to view overflowed content on mobile menu

### ISSUE THREAD

**Issue by matt-downs** [demiscient/demitheme#32]
If here are enough product categories or regular menu items, the mobile menu will become longer than the height of the screen. As the menu is fixed to the top of the page, there is no way to scroll and see these overflowed menu items. 

The following CSS should fix this issue by limiting the height of the expanded menu to the height of the screen - the height of the top navbar:
```css
.mobile-menu .navbar-nav {
	max-height: calc(100vh - 40px);
	overflow: auto;
}
```
